# Generated by Django 5.2 on 2025-05-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_orderitems_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillmentstatus',
            name='OrderStatus',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Paid', 'Paid'), ('Printing', 'Printing'), ('Shipped', 'Shipped'), ('Canceled', 'Canceled'), ('Refunded', 'Refunded')], default='Draft', max_length=20),
        ),
    ]
