# Generated by Django 5.2.1 on 2025-05-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_alter_models_filepath"),
    ]

    operations = [
        migrations.AlterField(
            model_name="models",
            name="Thumbnail",
            field=models.ImageField(null=True, upload_to="thumbnails/"),
        ),
    ]
