# Generated by Django 5.2.1 on 2025-05-14 14:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_alter_models_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="models",
            name="BaseInfill",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.3"),
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="orderitems",
            name="Markup",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.15"),
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(Decimal("1.00"))],
            ),
        ),
    ]
