# Generated by Django 5.2 on 2025-05-23 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_orders_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filament',
            name='ColorHexCode',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^[0-9A-Fa-f]{6}$')]),
        ),
    ]
